- name: Azure AD roles documentation
  href: index.yml
- name: Overview
  items:
  - name: What is Azure AD RBAC?
    href: custom-overview.md
- name: Quickstarts
  items:
  - name: Assign roles to users
    href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Concepts
  items:
  - name: Understand Azure AD roles
    href: concept-understand-roles.md
  - name: Compare roles
    items:
    - name: Compare Azure and Azure AD roles    
      href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Microsoft 365 roles
      href: m365-workload-docs.md
  - name: Group-based role assignments
    href: groups-concept.md
  - name: Administrative units  
    href: administrative-units.md
  - name: Best practices
    href: best-practices.md
  - name: Security
    items:
    - name: Role security planning
      href: security-planning.md
    - name: Create emergency accounts
      href: security-emergency-access.md
- name: How-to guides
  items:
  - name: List role definitions
    href: role-definitions-list.md
  - name: List role assignments
    items: 
    - name: List role assignments
      href: view-assignments.md
    - name: List role assignments for groups
      href: groups-view-assignments.md
  - name: Assign roles
    items:
    - name: Assign roles to users
      href: manage-roles-portal.md
    - name: Create a role-assignable group
      href: groups-create-eligible.md
    - name: Assign roles to groups
      href: groups-assign-role.md
    - name: Make a group eligible for a role in PIM
      href: groups-pim-eligible.md
    - name: Assign roles with scope using PowerShell
      href: custom-assign-powershell.md
    - name: Assign roles using Graph API
      href: custom-assign-graph.md
  - name: Remove role assignments
    items: 
    - name: Remove role assignments from groups
      href: groups-remove-assignment.md
  - name: Create custom roles
    items: 
    - name: Create a custom role
      href: custom-create.md
    - name: Create custom roles for enterprise apps
      href: custom-enterprise-apps.md
    - name: Create unlimited app registrations
      href: quickstart-app-registration-limits.md
  - name: Administrative units
    items:
    - name: Add and manage
      href: admin-units-manage.md
    - name: Add and manage users
      href: admin-units-add-manage-users.md
    - name: Add and manage groups
      href: admin-units-add-manage-groups.md
    - name: Assign a role with scope
      href: admin-units-assign-roles.md
  - name: Delegate
    items:
    - name: Delegate app admin role
      href: delegate-app-roles.md
    - name: My Staff delegation
      href: my-staff-configure.md
  - name: Troubleshoot
    items:
    - name: Troubleshoot roles assigned to groups
      href: groups-faq-troubleshooting.md
    - name: Troubleshoot administrative units
      href: admin-units-faq-troubleshoot.md
    - name: Get support for Azure AD
      href: ../fundamentals/active-directory-troubleshooting-support-howto.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Reference
  items:
  - name: Built-in roles
    href: permissions-reference.md
  - name: Least-privileged roles by task   
    href: delegate-by-task.md
  - name: Default user permissions    
    href: ../fundamentals/users-default-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
  - name: Custom role permissions
    items:
    - name: App registration permissions
      href: custom-available-permissions.md
    - name: Enterprise app permissions
      href: custom-enterprise-app-permissions.md
    - name: App consent permissions
      href: custom-consent-permissions.md
  - name: Azure AD service limits
    href: ../enterprise-users/directory-service-limits-restrictions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
  - name:  Azure AD PowerShell
    href: /powershell/azure/active-directory/overview
  - name: Graph API
    href: /graph/api/overview
