### YamlMime:Landing
title: Azure Arc Kubernetes (preview)
summary: Learn how to manage Kubernetes clusters with Azure Arc

metadata:
  title: Azure Arc Kubernetes
  description: Learn about how to manage on-premises machines in Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 

landingContent:
  - title: Connect Kubernetes clusters to Azure using Azure Arc
    linkLists: 
      - linkListType: overview
        links:
          - text: What is Azure Arc enabled Kubernetes?
            url: overview.md 
      - linkListType: quickstart
        links:
          - text: Connect cluster
            url: connect-cluster.md
      - linkListType: how-to-guide
        links:  
          - text: Deploy configurations using GitOps
            url: use-gitops-connected-cluster.md
          - text: Deploy Helm charts using GitOps
            url: use-gitops-with-helm.md
          - text: Enforce GitOps using Azure Policy
            url: use-azure-policy.md
          - text: Deploy Azure IoT edge workloads
            url: deploy-azure-iot-edge-workloads.md